//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhan_Xích_Thành_Đồ_án_BE__LTW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportReceipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ImportReceipt()
        {
            this.ImportDetails = new HashSet<ImportDetail>();
        }
    
        public int ImportID { get; set; }
        public int SupplierID { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public decimal TotalCost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportDetail> ImportDetails { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
